### PR TITLE
Feature/revert jquery upgrade

### PR DESCRIPTION
**Pull request by CloudNiner**
Upgrading jqueryUI to 1.11 within the project broke the resizable on the image export view. Since as far as I can tell there doesn't appear to be a technical reason to have upgraded, this reverts the jquery UI plugins to their original version

### CODE REVIEW

**Comment by CloudNiner** [comment]
Test failure is unrelated to this changeset. Restarted build, if it's still grumpy I'll investigate.

**Comment by fungjj92** [comment]
Lol the commit comments, seems fine +1
Should post to channel to update our subprojects

**Comment by CloudNiner** [comment]
Good call.

**Comment by flibbertigibbet** [comment]
There were specific technical reasons for the jQuery upgrade and file additions, related to needing to add the draggable component in order to support draggable legends.

**Comment by CloudNiner** [comment]
Ah. I assumed that was the case, there was a bug in the draggable after reverting and adding the older version of the draggable lib that I had to fix. But everything seemed to work fine afterwards.

**Comment by flibbertigibbet** [comment]
Ah okay, that was probably the bug that led me to upgrade the version.

**Pull request merged**
